# Generated by Django 4.2.3 on 2023-08-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=150)),
                ('author', models.CharField(db_column='Author', max_length=150)),
                ('year_published', models.DateTimeField(db_column='Year Published')),
                ('type', models.IntegerField(db_column='Type')),
            ],
            options={
                'db_table': 'Book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loandate', models.DateTimeField(db_column='Loandate')),
                ('returndate', models.IntegerField(db_column='Returndate')),
            ],
            options={
                'db_table': 'Loan',
                'managed': False,
            },
        ),
    ]
