# Generated by Django 4.2.3 on 2023-08-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_book_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'Customer',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.AlterModelTable(
            name='djangomigrations',
            table='django_session',
        ),
    ]
